qcacmn: add 'const' for 'section' in struct TGT_REG_TABLE
To fix the following compilation error:
warning: assignment discards ‘const’
qualifier from pointer target type, at:
reg_table->section = ar6320v2_reg_table
in ol_fw.c.

It's because the register table is a
const array, while reg_table->section does
not point to a const.
So add 'const' for 'section'.

Change-Id: Idfef358817241e73d660d2730b74c2ca88e23af1
CRs-Fixed: 2017786