ext4: ext4_find_entry requires 5 agrumemts
* Needed after upstream commit 1523c07d6df41c9f051c2aeaa47975345c75fb60 being that moto added an
  additional flag to ext4_find_entry in this commit ee9b786a457177693eaf1abf7338f76b20a32852.

* Fixes:
   fs/ext4/namei.c:3395:70: error: too few arguments to function
   call, expected 5, have 4

Change-Id: I9ca1066b5f329456d5edeb7a649bd02d1c11ee2a